### ISSUE TITLE
BCSTMs without loop points will loop to the beginning

### ISSUE THREAD

**Issue by PlatinumLucario** [NPI-D7/BCSTM-Player#1]
I can't see any reported issue on this, and while I haven't tried out the latest Nightly build to find out if it's still occurring, but NW4C Soundmaker Streamed Audio Binaries (BCSTM) without a loop points assigned in its data will continue to loop, instead of stopping when it gets to the end of the file. Only BCSTMs with loop points assigned in its data should be allowed to loop.

Edit: I have tested out the latest nightly, and it still has this issue.

**Comment by Tobi-D7** [comment]
I don't think that this is actually a bug or something because there's a bool function defined in the BCSTM header wether it should loop or not

**Comment by Tobi-D7** [comment]
```
m_looping = read8();
m_blockLoopStart = loopPos / m_blockSampleCount;
m_blockLoopEnd = (loopEnd % m_blockSampleCount ? m_blockCount : loopEnd / m_blockSampleCount);

```

sample for loops

**Comment by Tobi-D7** [comment]
i found the problem and fixed it
