### ISSUE TITLE
Selecting the same currently playing BCSTM breaks sound functionality

### ISSUE THREAD

**Issue by PlatinumLucario** [NPI-D7/BCSTM-Player#2]
If there is a BCSTM file playing and the same file is selected more than once, it can cause the sound to no longer work until the app is restarted. This could be related to the File Browser bug, but I'm not entirely sure.

Steps to reproduce:
1. Select any BCSTM.
2. Select it again.
3. If there still is sound, select it again.

If these steps are done correctly, the sound will have ceased to function.

**Comment by Tobi-D7** [comment]
I think this seems to be fixed
